In [2]:
import pandas as pd
spray=pd.read_csv('../../input/clean/spray_cleaned.csv').drop(['Unnamed: 0'],axis=1)
train=pd.read_csv('../../input/clean/train_cleaned.csv').drop(['Unnamed: 0'],axis=1)
weather=pd.read_csv('weather_agged.csv').drop(['Unnamed: 0'],axis=1)
test=pd.read_csv('../../input/clean/test_cleaned.csv').drop(['Unnamed: 0', 'Id'],axis=1)

In [ ]:
weather['Date']=pd.to_datetime(weather['Date'])
test['Date']=pd.to_datetime(test['Date'])
train['Date']=pd.to_datetime(train['Date'])
spray['Date']=pd.to_datetime(spray['Date'])

In [ ]:
def spray_factor(row):
    Date = row.Date
    Lat = row.Lat
    Long = row.Long   
    rel=spray[(spray['Date']<Date) & ((Date-spray['Date'])<pd.Timedelta('14 days'))]
    s=0
    for _ in rel.iterrows():
        latdiff=Lat-_[1]['Lat']
        longdiff=Long-_[1]['Long']
        dis=.5**(latdiff**2+longdiff**2)
        t=(Date-_[1]['Date']).days
        s+=(.5)**(t/1.5)/dis
    return s

In [ ]:
train['spray_factor'] = train.apply(spray_factor, axis=1)
train_df=train.merge(weather, on='Date')
test['spray_factor'] = test.apply(spray_factor, axis=1)
test_df=test.merge(weather, on='Date')

base species: pipiens/restuans
base trap: T115
DUMMIFY TRAP, DROP T115, DROP TRAP
DROP SPECIES
CONVERT DATES TO NUMBERS

In [ ]:
train.Species.value_counts()

In [ ]:
test.Species.value_counts()

In [ ]:
train['ERR'].sum()

In [ ]:
test.columns.values

In [ ]:
len(train)

In [ ]:
len(test)

In [ ]:
weather

In [ ]:
train

In [2]:
train.shape

(8603, 14)

In [3]:
train.merge(weather).shape

(8603, 52)

In [5]:
weather.describe()

,Temp_Min,Temp_Max,Temp_Avg,Temp_Dew_Point,StnPressure,Day_Length,Ht_Cool,PrecipTotal,Temp_Min1,Temp_Min2,Temp_Min4,Temp_Min7,Temp_Min10,Temp_Min14,Temp_Max1,Temp_Max2,Temp_Max4,Temp_Max7,Temp_Max10,Temp_Max14,Temp_Dew_Point1,Temp_Dew_Point2,Temp_Dew_Point4,Temp_Dew_Point7,Temp_Dew_Point10,Temp_Dew_Point14,Temp_Avg1,Temp_Avg2,Temp_Avg4,Temp_Avg7,Temp_Avg10,Temp_Avg14,PrecipTotal1,PrecipTotal2,PrecipTotal4,PrecipTotal7,PrecipTotal10,PrecipTotal14
count,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000
mean,57.810462,76.166101,67.223505,53.457880,29.284468,820.179348,-1.606658,0.134538,57.787704,55.747622,53.335598,51.258492,49.960258,48.703804,76.133492,78.853261,81.949389,84.269361,85.574389,86.669158,53.439538,55.731318,58.776155,61.220788,62.543139,63.571671,67.195652,67.157948,67.087296,66.970497,66.849524,66.690606,0.134518,0.269035,0.538071,0.941624,1.345088,1.882779
std,10.270115,11.424705,10.513691,10.649199,0.155495,89.392210,10.511437,0.421066,10.360740,10.376724,10.404309,10.506412,10.662214,10.882612,11.572695,11.071282,10.506739,10.380489,10.613973,11.162750,10.717833,10.287769,9.496001,8.836022,8.658370,8.799959,10.636800,10.424852,10.205482,10.199311,10.380199,10.730635,0.421072,0.638425,0.924981,1.247952,1.505251,1.816617
min,29.000000,41.500000,36.000000,22.500000,28.590000,624.000000,-28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50.500000,68.500000,60.500000,46.000000,29.195000,751.000000,-10.000000,0.000000,50.500000,48.375000,45.000000,43.000000,41.500000,40.500000,68.500000,72.000000,77.000000,79.875000,82.500000,84.000000,46.000000,49.000000,53.375000,56.000000,58.500000,60.000000,60.500000,60.250000,60.250000,60.285714,60.437500,60.562500,0.000000,0.000000,0.010000,0.190000,0.410000,0.680000
50%,59.500000,78.500000,69.000000,54.500000,29.290000,854.000000,-3.000000,0.000000,59.500000,57.000000,55.000000,53.500000,51.500000,50.500000,78.500000,81.000000,84.000000,86.500000,88.000000,89.000000,54.500000,57.000000,60.500000,63.000000,64.500000,65.500000,69.000000,68.750000,68.875000,69.035714,69.300000,69.285714,0.000000,0.010000,0.215000,0.550000,0.920000,1.370000
75%,65.500000,84.500000,75.500000,61.500000,29.380000,897.250000,5.000000,0.060000,65.500000,64.000000,61.500000,59.500000,58.500000,57.500000,84.500000,86.500000,89.000000,90.500000,91.500000,92.000000,61.500000,64.000000,66.000000,67.500000,68.500000,69.000000,75.500000,75.000000,74.625000,74.160714,73.850000,73.687500,0.060000,0.280000,0.682500,1.200000,1.790000,2.530000
max,82.500000,103.500000,93.500000,74.500000,29.825000,914.000000,29.000000,6.860000,82.500000,79.000000,77.000000,71.500000,70.000000,70.000000,103.500000,103.500000,103.500000,103.500000,103.500000,103.500000,74.500000,74.500000,74.500000,74.500000,74.500000,74.500000,93.500000,92.250000,90.500000,87.500000,86.050000,83.785714,6.860000,8.410000,8.610000,10.000000,11.150000,12.610000

In [4]:
pd.options.display.max_columns=100